# Generated by Django 3.0.5 on 2021-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210502_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
