# Generated by Django 3.0.5 on 2021-05-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210502_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default="{user.first_name + ' ' + user.last_name}", max_length=100),
        ),
    ]
