# Generated by Django 3.0.5 on 2021-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
