# Generated by Django 3.0.5 on 2021-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20210503_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skils',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
